-- 접속자 확인
SELECT USER FROM DUAL;

CREATE TABLE MEMBER (
	ID NUMBER PRIMARY KEY,
	EMAIL VARCHAR(255) UNIQUE,
	PASSWORD VARCHAR(100),
	NAME VARCHAR(100),
	REGDATE DATE
);

-- 시퀀스 생성
CREATE SEQUENCE MEMBER_ID_SEQ START WITH 1 INCREMENT BY 1;

-- 트리거 생성
CREATE OR REPLACE TRIGGER TRI_MEMBER_ID_SEQ
	BEFORE INSERT ON MEMBER FOR EACH ROW
BEGIN 
	IF INSERTING AND :NEW.ID IS NULL THEN 
		SELECT MEMBER_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END IF;
END;


